"""
Test that the broken get_by_text("role=link[name=...]") pattern is now
correctly parsed and regenerated as page.get_by_role(...).
"""
from app.services.recorder import PlaywrightScriptParser
from app.services.script_generator import ScriptGenerator

# Build the broken script lines directly (no escaping issues)
broken_lines = [
    'import asyncio',
    'from playwright.async_api import async_playwright',
    '',
    'async def run():',
    '    async with async_playwright() as p:',
    '        browser = await p.chromium.launch(headless=False)',
    '        context = await browser.new_context()',
    '        page = await context.new_page()',
    '',
    '        await page.goto("https://petstore.octoperf.com/actions/Catalog.action")',
    '        await page.get_by_text("role=link[name=\\"Dogs\\"]").click()',
    '        await page.get_by_text("role=link[name=\\"K9-BD-\\"]").click()',
    '        await page.get_by_text("role=link[name=\\"Return to DOGS\\"]").click()',
    '        await page.get_by_text("role=link[name=\\"Add to Cart\\"]").click()',
    '        await browser.close()',
    '',
    'asyncio.run(run())',
]

# Show actual line content
print("Line 10:", repr(broken_lines[10]))
# → 'await page.get_by_text("role=link[name=\\"Dogs\\"]").click()'
# The \\" in Python source is \" in the actual string which is " in the script

# Create actual script with real backslash-quote escapes that Playwright codegen would write
broken_script = '\n'.join(broken_lines)
print("Actual script line:", broken_script.split('\n')[10])

# Alternatively, test with the simpler form the user shows in their question
# The user's screenshot shows:
# await page.get_by_text("role=link[name="Dogs"]").click()
# which with proper escaping in a .py file would be:
# await page.get_by_text('role=link[name="Dogs"]').click()

print()
print("=== Test with single-quoted get_by_text (actual user case) ===")

user_script_lines = [
    'import asyncio',
    'from playwright.async_api import async_playwright',
    '',
    'async def run():',
    '    async with async_playwright() as p:',
    '        browser = await p.chromium.launch(headless=False)',
    '        context = await browser.new_context()',
    '        page = await context.new_page()',
    '',
    '        await page.goto("https://petstore.octoperf.com/actions/Catalog.action")',
    "        await page.get_by_text('role=link[name=\"Dogs\"]').click()",
    "        await page.get_by_text('role=link[name=\"K9-BD-\"]').click()",
    "        await page.get_by_text('role=link[name=\"Return to DOGS\"]').click()",
    "        await page.get_by_text('role=link[name=\"K9-BD-\"]').click()",
    "        await page.get_by_text('role=link[name=\"Add to Cart\"]').click()",
    '        await browser.close()',
    '',
    'asyncio.run(run())',
]

user_script = '\n'.join(user_script_lines)
print("Sample line:", user_script_lines[10])

nodes = PlaywrightScriptParser.parse(user_script)
for n in nodes:
    cfg = n.get('config', {})
    sel = cfg.get('selector', cfg.get('url', ''))
    print("  " + n['node_type'] + " | selector=" + sel)

edges = []
for i in range(1, len(nodes)):
    edges.append({
        "edge_id": "edge_" + str(i),
        "source_node_id": nodes[i-1]["node_id"],
        "target_node_id": nodes[i]["node_id"],
    })

print()
print("=== Generated script ===")
code = ScriptGenerator.generate(nodes=nodes, edges=edges, language="python", include_comments=True)
print(code)

# Assertions
assert "get_by_role" in code, "FAIL: get_by_role not found"
assert 'get_by_role("link", name="Dogs")' in code, "FAIL: Dogs not correctly generated"
assert 'get_by_role("link", name="K9-BD-")' in code, "FAIL: K9-BD- not correctly generated"
assert 'get_by_role("link", name="Add to Cart")' in code, "FAIL: Add to Cart not correctly generated"
assert "# Generated by TaskMaster" in code, "FAIL: Header wrong"
print("=== ALL ASSERTIONS PASSED ===")

# Also test what happens with the extract_selector directly
print()
print("=== Direct _extract_selector tests ===")
test_lines = [
    'await page.get_by_text(\'role=link[name="Dogs"]\').click()',
    'await page.get_by_text("role=link[name=\\"Dogs\\"]").click()',
    'await page.get_by_text("Submit").click()',
    'await page.get_by_text(\'role=button[name="Find Flights"]\').click()',
]
for line in test_lines:
    sel = PlaywrightScriptParser._extract_selector(line)
    print("  Line: " + line)
    print("  Sel:  " + sel)
    print()
