"""
Desktop Script Generator — exports workflow desktop nodes as a runnable PyAutoGUI Python script.
Fully backward-compatible: web nodes are skipped (or can be mixed in a hybrid export).
"""
from __future__ import annotations

from typing import Any, Dict, List


# ── Helpers ───────────────────────────────────────────────────────────────────

_DESKTOP_NODE_TYPES = {
    "DESKTOP_CLICK",
    "DESKTOP_TYPE",
    "DESKTOP_HOTKEY",
    "DESKTOP_MOVE",
    "DESKTOP_DRAG",
    "DESKTOP_SCROLL",
    "DESKTOP_SCREENSHOT",
    "DESKTOP_FIND_IMAGE",
    "DESKTOP_LAUNCH_APP",
    "DESKTOP_CLOSE_APP",
    "DESKTOP_SWITCH_WINDOW",
}

_WEB_NODE_TYPES = {
    "CLICK", "TYPE", "SELECT", "HOVER", "UPLOAD_FILE",
    "OPEN_URL", "BACK", "REFRESH",
}


def _is_desktop(node_type: str) -> bool:
    return node_type in _DESKTOP_NODE_TYPES


def _is_web(node_type: str) -> bool:
    return node_type in _WEB_NODE_TYPES


# ── Main generator class ──────────────────────────────────────────────────────

class DesktopScriptGenerator:
    """Generate a PyAutoGUI Python script from workflow nodes."""

    @staticmethod
    def generate(
        nodes: List[Dict[str, Any]],
        include_comments: bool = True,
        mode: str = "desktop",          # "desktop" | "hybrid"
    ) -> str:
        """
        Args:
            nodes:            workflow nodes (already topologically sorted by caller)
            include_comments: emit label comments before each action
            mode:             "desktop"  → only desktop nodes
                              "hybrid"   → desktop nodes + Playwright stubs for web nodes
        """
        lines: List[str] = []

        has_desktop = any(_is_desktop(n.get("node_type", "")) for n in nodes)
        has_web = any(_is_web(n.get("node_type", "")) for n in nodes)
        has_delay = any(n.get("node_type") == "DELAY" for n in nodes)
        has_subprocess = any(n.get("node_type") == "DESKTOP_LAUNCH_APP" for n in nodes)
        has_win32 = any(
            n.get("node_type") in ("DESKTOP_CLOSE_APP", "DESKTOP_SWITCH_WINDOW")
            for n in nodes
        )

        # ── File header ──────────────────────────────────────────────────────
        if include_comments:
            lines.append("# Generated by IBMTaskWeaver - Desktop / Hybrid Automation Script")
            lines.append("# Requires: pyautogui  (pip install pyautogui)")
            if mode == "hybrid":
                lines.append("# Requires: playwright (pip install playwright && playwright install chromium)")
            if has_win32:
                lines.append("# Requires: pywin32   (pip install pywin32)")
            lines.append("")

        # ── Imports ──────────────────────────────────────────────────────────
        lines.append("import pyautogui")
        if has_delay:
            lines.append("import time")
        if has_subprocess:
            lines.append("import subprocess")
        if has_win32:
            lines.append("import win32gui")
            lines.append("import win32con")
        if mode == "hybrid" and has_web:
            lines.append("import asyncio")
            lines.append("from playwright.async_api import async_playwright")

        lines.append("")
        lines.append("# Safety: move mouse to corner to abort")
        lines.append("pyautogui.FAILSAFE = True")
        lines.append("pyautogui.PAUSE = 0.05  # 50 ms pause between actions")
        lines.append("")

        # ── Hybrid: open Playwright browser in parallel ───────────────────────
        if mode == "hybrid" and has_web:
            lines.append("# -- Hybrid setup: Playwright browser --")
            lines.append("_pw = None")
            lines.append("_browser = None")
            lines.append("_page = None")
            lines.append("")
            lines.append("async def _init_browser():")
            lines.append("    global _pw, _browser, _page")
            lines.append("    _pw = await async_playwright().start()")
            lines.append("    _browser = await _pw.chromium.launch(headless=False)")
            lines.append("    _page = await _browser.new_context()")
            lines.append("    _page = _page.new_page()")
            lines.append("")
            lines.append("")

        # ── Main function ─────────────────────────────────────────────────────
        if mode == "hybrid" and has_web:
            lines.append("async def run():")
        else:
            lines.append("def run():")

        indent = "    "

        for node in nodes:
            node_type = node.get("node_type", "")
            config = node.get("config", {})
            label = node.get("label", "")

            if include_comments and label:
                lines.append(f"{indent}# {label}")

            # ── DESKTOP nodes ─────────────────────────────────────────────────
            if node_type == "DESKTOP_CLICK":
                x = config.get("x", 0)
                y = config.get("y", 0)
                btn = config.get("button", "left")
                clicks = config.get("clicks", 1)
                if clicks == 2:
                    lines.append(f"{indent}pyautogui.doubleClick({x}, {y})")
                elif btn == "right":
                    lines.append(f"{indent}pyautogui.click({x}, {y}, button='right')")
                elif btn == "middle":
                    lines.append(f"{indent}pyautogui.click({x}, {y}, button='middle')")
                else:
                    lines.append(f"{indent}pyautogui.click({x}, {y})")

            elif node_type == "DESKTOP_TYPE":
                text = config.get("text", "")
                escaped = text.replace("\\", "\\\\").replace("'", "\\'")
                lines.append(f"{indent}pyautogui.typewrite('{escaped}', interval=0.05)")

            elif node_type == "DESKTOP_HOTKEY":
                keys_raw = config.get("keys", "")
                key_list = [f"'{k.strip()}'" for k in keys_raw.split("+") if k.strip()]
                lines.append(f"{indent}pyautogui.hotkey({', '.join(key_list)})")

            elif node_type == "DESKTOP_MOVE":
                x = config.get("x", 0)
                y = config.get("y", 0)
                duration = config.get("duration", 0.25)
                lines.append(f"{indent}pyautogui.moveTo({x}, {y}, duration={duration})")

            elif node_type == "DESKTOP_DRAG":
                from_x = config.get("from_x", 0)
                from_y = config.get("from_y", 0)
                to_x = config.get("to_x", 0)
                to_y = config.get("to_y", 0)
                duration = config.get("duration", 0.5)
                if from_x or from_y:
                    lines.append(f"{indent}pyautogui.moveTo({from_x}, {from_y})")
                lines.append(f"{indent}pyautogui.dragTo({to_x}, {to_y}, duration={duration}, button='left')")

            elif node_type == "DESKTOP_SCROLL":
                x = config.get("x", 0)
                y = config.get("y", 0)
                dy = config.get("dy", -3)
                if x or y:
                    lines.append(f"{indent}pyautogui.moveTo({x}, {y})")
                lines.append(f"{indent}pyautogui.scroll({dy})")

            elif node_type == "DESKTOP_SCREENSHOT":
                path = config.get("path", "screenshot.png")
                escaped_path = path.replace("\\", "/")
                lines.append(f"{indent}pyautogui.screenshot('{escaped_path}')")

            elif node_type == "DESKTOP_FIND_IMAGE":
                image = config.get("image_path", "target.png")
                var_name = config.get("result_variable", "_img_loc")
                confidence = config.get("confidence", 0.9)
                lines.append(f"{indent}{var_name} = pyautogui.locateOnScreen('{image}', confidence={confidence})")
                lines.append(f"{indent}if {var_name}:")
                lines.append(f"{indent}    pyautogui.click(pyautogui.center({var_name}))")

            elif node_type == "DESKTOP_LAUNCH_APP":
                app_path = config.get("app_path", "notepad.exe")
                escaped = app_path.replace("\\", "\\\\")
                lines.append(f"{indent}subprocess.Popen(r'{escaped}')")
                lines.append(f"{indent}pyautogui.sleep(1.5)  # wait for app to open")

            elif node_type == "DESKTOP_CLOSE_APP":
                title = config.get("window_title", "")
                if title:
                    lines.append(f"{indent}hwnd = win32gui.FindWindow(None, '{title}')")
                    lines.append(f"{indent}if hwnd:")
                    lines.append(f"{indent}    win32gui.PostMessage(hwnd, win32con.WM_CLOSE, 0, 0)")
                else:
                    lines.append(f"{indent}pyautogui.hotkey('alt', 'f4')")

            elif node_type == "DESKTOP_SWITCH_WINDOW":
                title = config.get("window_title", "")
                if title:
                    lines.append(f"{indent}hwnd = win32gui.FindWindow(None, '{title}')")
                    lines.append(f"{indent}if hwnd:")
                    lines.append(f"{indent}    win32gui.SetForegroundWindow(hwnd)")

            # ── WEB nodes (hybrid mode only) ─────────────────────────────────
            elif mode == "hybrid" and node_type == "OPEN_URL":
                url = config.get("url", "")
                lines.append(f"{indent}await _page.goto('{url}')")
                lines.append(f"{indent}await _page.wait_for_load_state('networkidle')")

            elif mode == "hybrid" and node_type == "CLICK":
                selector = config.get("selector", "")
                lines.append(f"{indent}await _page.locator(\"{selector}\").click()")

            elif mode == "hybrid" and node_type == "TYPE":
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f"{indent}await _page.locator(\"{selector}\").fill(\"{value}\")")

            elif mode == "hybrid" and node_type == "SELECT":
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f"{indent}await _page.locator(\"{selector}\").select_option(\"{value}\")")

            # ── DELAY (shared) ────────────────────────────────────────────────
            elif node_type == "DELAY":
                duration_ms = config.get("duration", 1000)
                lines.append(f"{indent}time.sleep({duration_ms / 1000})")

            else:
                if include_comments:
                    lines.append(f"{indent}# TODO: {node_type} — not yet implemented in desktop script")

            lines.append("")

        lines.append("")

        # ── Entry point ───────────────────────────────────────────────────────
        if mode == "hybrid" and has_web:
            lines.append("asyncio.run(run())")
        else:
            lines.append("if __name__ == '__main__':")
            lines.append("    run()")

        return "\n".join(lines)


# Made with Bob
