"""
Playwright Script Generator
"""
from typing import Dict, List, Any
from app.db.models import NodeType


class ScriptGenerator:
    """Generate Playwright scripts from workflow nodes"""
    
    @staticmethod
    def generate(
        nodes: List[Dict[str, Any]],
        edges: List[Dict[str, Any]],
        language: str = "python",
        include_comments: bool = True
    ) -> str:
        """Generate Playwright script from workflow"""
        if language == "python":
            return ScriptGenerator._generate_python(nodes, edges, include_comments)
        elif language == "javascript":
            return ScriptGenerator._generate_javascript(nodes, edges, include_comments)
        elif language == "typescript":
            return ScriptGenerator._generate_typescript(nodes, edges, include_comments)
        else:
            raise ValueError(f"Unsupported language: {language}")
    
    @staticmethod
    def _generate_python(
        nodes: List[Dict[str, Any]],
        edges: List[Dict[str, Any]],
        include_comments: bool
    ) -> str:
        """Generate Python Playwright script"""
        lines = []
        
        # Header
        if include_comments:
            lines.append("# Generated by TaskMaster")
            lines.append("# Playwright Python Script")
            lines.append("")
        
        lines.append("import asyncio")
        lines.append("from playwright.async_api import async_playwright")
        lines.append("")
        lines.append("async def run():")
        lines.append("    async with async_playwright() as p:")
        lines.append("        browser = await p.chromium.launch(headless=False)")
        lines.append("        context = await browser.new_context()")
        lines.append("        page = await context.new_page()")
        lines.append("")
        
        # Generate code for each node
        for node in nodes:
            node_type = node.get("node_type")
            config = node.get("config", {})
            label = node.get("label", "")
            
            if include_comments and label:
                lines.append(f"        # {label}")
            
            if node_type == NodeType.OPEN_URL.value:
                url = config.get("url", "")
                lines.append(f'        await page.goto("{url}")')
            
            elif node_type == NodeType.CLICK.value:
                selector = config.get("selector", "")
                lines.append(f'        await page.get_by_text("{selector}").click()')
            
            elif node_type == NodeType.TYPE.value:
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f'        await page.get_by_label("{selector}").fill("{value}")')
            
            elif node_type == NodeType.SELECT.value:
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f'        await page.locator("{selector}").select_option("{value}")')
            
            elif node_type == NodeType.HOVER.value:
                selector = config.get("selector", "")
                lines.append(f'        await page.locator("{selector}").hover()')
            
            elif node_type == NodeType.UPLOAD_FILE.value:
                selector = config.get("selector", "")
                lines.append(f'        await page.locator("{selector}").set_input_files("path/to/file")')
            
            elif node_type == NodeType.DELAY.value:
                duration = config.get("duration", 1000) / 1000
                lines.append(f"        await page.wait_for_timeout({int(duration * 1000)})")
            
            elif node_type == NodeType.BACK.value:
                lines.append("        await page.go_back()")
            
            elif node_type == NodeType.REFRESH.value:
                lines.append("        await page.reload()")
            
            lines.append("")
        
        # Footer
        lines.append("        await browser.close()")
        lines.append("")
        lines.append("asyncio.run(run())")
        
        return "\n".join(lines)
    
    @staticmethod
    def _generate_javascript(
        nodes: List[Dict[str, Any]],
        edges: List[Dict[str, Any]],
        include_comments: bool
    ) -> str:
        """Generate JavaScript Playwright script"""
        lines = []
        
        # Header
        if include_comments:
            lines.append("// Generated by TaskMaster")
            lines.append("// Playwright JavaScript Script")
            lines.append("")
        
        lines.append("const { chromium } = require('playwright');")
        lines.append("")
        lines.append("(async () => {")
        lines.append("  const browser = await chromium.launch({ headless: false });")
        lines.append("  const context = await browser.newContext();")
        lines.append("  const page = await context.newPage();")
        lines.append("")
        
        # Generate code for each node
        for node in nodes:
            node_type = node.get("node_type")
            config = node.get("config", {})
            label = node.get("label", "")
            
            if include_comments and label:
                lines.append(f"  // {label}")
            
            if node_type == NodeType.OPEN_URL.value:
                url = config.get("url", "")
                lines.append(f"  await page.goto('{url}');")
            
            elif node_type == NodeType.CLICK.value:
                selector = config.get("selector", "")
                lines.append(f"  await page.getByText('{selector}').click();")
            
            elif node_type == NodeType.TYPE.value:
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f"  await page.getByLabel('{selector}').fill('{value}');")
            
            elif node_type == NodeType.SELECT.value:
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f"  await page.locator('{selector}').selectOption('{value}');")
            
            elif node_type == NodeType.HOVER.value:
                selector = config.get("selector", "")
                lines.append(f"  await page.locator('{selector}').hover();")
            
            elif node_type == NodeType.UPLOAD_FILE.value:
                selector = config.get("selector", "")
                lines.append(f"  await page.locator('{selector}').setInputFiles('path/to/file');")
            
            elif node_type == NodeType.DELAY.value:
                duration = config.get("duration", 1000)
                lines.append(f"  await page.waitForTimeout({duration});")
            
            elif node_type == NodeType.BACK.value:
                lines.append("  await page.goBack();")
            
            elif node_type == NodeType.REFRESH.value:
                lines.append("  await page.reload();")
            
            lines.append("")
        
        # Footer
        lines.append("  await browser.close();")
        lines.append("})();")
        
        return "\n".join(lines)
    
    @staticmethod
    def _generate_typescript(
        nodes: List[Dict[str, Any]],
        edges: List[Dict[str, Any]],
        include_comments: bool
    ) -> str:
        """Generate TypeScript Playwright script"""
        lines = []
        
        # Header
        if include_comments:
            lines.append("// Generated by TaskMaster")
            lines.append("// Playwright TypeScript Script")
            lines.append("")
        
        lines.append("import { chromium } from 'playwright';")
        lines.append("")
        lines.append("(async () => {")
        lines.append("  const browser = await chromium.launch({ headless: false });")
        lines.append("  const context = await browser.newContext();")
        lines.append("  const page = await context.newPage();")
        lines.append("")
        
        # Generate code for each node
        for node in nodes:
            node_type = node.get("node_type")
            config = node.get("config", {})
            label = node.get("label", "")
            
            if include_comments and label:
                lines.append(f"  // {label}")
            
            if node_type == NodeType.OPEN_URL.value:
                url = config.get("url", "")
                lines.append(f"  await page.goto('{url}');")
            
            elif node_type == NodeType.CLICK.value:
                selector = config.get("selector", "")
                lines.append(f"  await page.getByText('{selector}').click();")
            
            elif node_type == NodeType.TYPE.value:
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f"  await page.getByLabel('{selector}').fill('{value}');")
            
            elif node_type == NodeType.SELECT.value:
                selector = config.get("selector", "")
                value = config.get("value", "")
                lines.append(f"  await page.locator('{selector}').selectOption('{value}');")
            
            elif node_type == NodeType.HOVER.value:
                selector = config.get("selector", "")
                lines.append(f"  await page.locator('{selector}').hover();")
            
            elif node_type == NodeType.UPLOAD_FILE.value:
                selector = config.get("selector", "")
                lines.append(f"  await page.locator('{selector}').setInputFiles('path/to/file');")
            
            elif node_type == NodeType.DELAY.value:
                duration = config.get("duration", 1000)
                lines.append(f"  await page.waitForTimeout({duration});")
            
            elif node_type == NodeType.BACK.value:
                lines.append("  await page.goBack();")
            
            elif node_type == NodeType.REFRESH.value:
                lines.append("  await page.reload();")
            
            lines.append("")
        
        # Footer
        lines.append("  await browser.close();")
        lines.append("})();")
        
        return "\n".join(lines)

# Made with Bob
